version: '3'
services:
    postgresql_database:
        image: postgres:11.1
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./docker-postgres/init-sqls:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=store
        ports:
            - 4321:5432
            
    spring:
        build:
            dockerfile: Dockerfile
            context: ./
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_database:5432/store
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
        depends_on:
            - postgresql_database
        ports:
            - 8888:8080
        volumes:
            - D:\IT Projects\spring-boot-practice-files:/extra

    keycloak:
        image: quay.io/keycloak/keycloak:14.0.0
        container_name: keycloak
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
            - 8081:8080
        restart: always
        volumes:
            - keycloakData:/opt/jboss/keycloak/standalone/data/

volumes:
    pgdata:
        driver: local
    keycloakData:
        driver: local