spring:
  jpa:
    hibernate.ddl-auto : none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

  # for schema.sql and data.sql initialization
#  datasource.initialization-mode : never/ always

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: qbssystem!
#    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
